package com.example.footballtournamentsimulator.team;

//TODO: ALO - remove unused names.
public enum TeamName {
    AJAX,
    ATALANTA,
    ATLETICO_MADRID,
    BARCELONA,
    BAYERN_LEVERKUSEN,
    BAYERN_MUNICH,
    BENFICA,
    BORUSSIA_MOENCHENGLADBACH,
    CHELSEA,
    CLUB_BRUGGE,
    DORTMUND,
    DYNAMO_KYIV,
    FC_BARCELONA,
    FC_PORTO,
    INTER_MILAN,
    JUVENTUS,
    LAZIO,
    LEICESTER_CITY,
    LILLE,
    LIVERPOOL,
    LOKOMOTIV_MOSCOW,
    MANCHESTER_CITY,
    MANCHESTER_UNITED,
    MARSEILLE,
    MILAN,
    MONACO,
    NAPOLI,
    PARIS_SAINT_GERMAIN,
    PORTO,
    RANGERS,
    RB_LEIPZIG,
    REAL_MADRID,
    RENNES,
    SEVILLA,
    SHAKHTAR_DONETSK,
    TOTTENHAM,
    VIKTORIA_PLZEN



}
